// Public-domain paintings from the Art Institute of Chicago open access
// collection. Generated by scripts/fetch-taste-corpus.mjs from the museum's API:
// do not edit by hand. Each entry keeps the museum's own id, so it can be
// checked at https://www.artic.edu/artworks/<id>.

export interface Artwork {
  id: number;
  title: string;
  artist: string;
  date: string;
  file: string; // under /public
}

export const CORPUS: Artwork[] = [];
