export interface PrecedentEntry {
  id: string;
  building_name: string;
  architect: string;
  year: number;
  location: string;
  program_type: string[];
  key_moves: string[];
  scale: "small" | "medium" | "large";
  climate: string;
  short_description: string;
}

export const PRECEDENTS: PrecedentEntry[] = [
  // Modernist canon
  {
    id: "salk-institute",
    building_name: "Salk Institute for Biological Studies",
    architect: "Louis Kahn",
    year: 1965,
    location: "La Jolla, California",
    program_type: ["research", "institutional"],
    key_moves: ["central void as public gesture", "served and servant spaces", "monumental materiality"],
    scale: "large",
    climate: "temperate coastal",
    short_description: "Two symmetrical research wings frame an empty plaza paved in travertine. The emptiness is the program.",
  },
  {
    id: "kim-bell",
    building_name: "Kimbell Art Museum",
    architect: "Louis Kahn",
    year: 1972,
    location: "Fort Worth, Texas",
    program_type: ["museum", "cultural"],
    key_moves: ["cycloidal vault lighting", "natural light for art", "cyclical plan"],
    scale: "medium",
    climate: "arid",
    short_description: "Vaulted concrete tubes admit soft north light to gallery spaces. Structure becomes the architectural idea.",
  },
  {
    id: "phillips-exeter",
    building_name: "Phillips Exeter Academy Library",
    architect: "Louis Kahn",
    year: 1972,
    location: "Exeter, New Hampshire",
    program_type: ["library", "educational", "institutional"],
    key_moves: ["monumental reading room", "structure as ornament", "brick materiality"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Nine-story brick cube with a 143-foot clearspan interior. Every major element is structural and visible.",
  },
  {
    id: "barcelona-pavilion",
    building_name: "German Pavilion Barcelona",
    architect: "Ludwig Mies van der Rohe",
    year: 1929,
    location: "Barcelona, Spain",
    program_type: ["pavilion", "exhibition"],
    key_moves: ["free plan", "transparency", "material purity"],
    scale: "small",
    climate: "temperate",
    short_description: "Travertine, marble, steel, and glass dissolve the boundary between interior and exterior.",
  },
  {
    id: "tugendhat",
    building_name: "Tugendhat House",
    architect: "Ludwig Mies van der Rohe",
    year: 1930,
    location: "Brno, Czech Republic",
    program_type: ["residential"],
    key_moves: ["open living floor", "floor-to-ceiling glass", "minimal structure"],
    scale: "medium",
    climate: "temperate continental",
    short_description: "A residential prototype for the open plan. Stone, steel, chrome, and glass orchestrate social space.",
  },
  {
    id: "villa-savoye",
    building_name: "Villa Savoye",
    architect: "Le Corbusier",
    year: 1931,
    location: "Poissy, France",
    program_type: ["residential"],
    key_moves: ["pilotis raising the house", "roof garden", "ribbon window", "ramp as circulation"],
    scale: "small",
    climate: "temperate",
    short_description: "Five points of modern architecture: pilotis, free facade, open plan, ribbon window, roof garden.",
  },
  {
    id: "monastery-sainte-marie",
    building_name: "Monastery of Sainte-Marie de la Tourette",
    architect: "Le Corbusier",
    year: 1960,
    location: "Eveux, France",
    program_type: ["religious", "institutional"],
    key_moves: ["brutal concrete form", "procession and sequence", "controlled light"],
    scale: "large",
    climate: "temperate",
    short_description: "Reinforced concrete monastery perched on a hillside. Monks' cells surround a cloister court; the church anchors the composition.",
  },
  {
    id: "pan-american-grace",
    building_name: "Pan American Grace Airways Terminal",
    architect: "Lina Bo Bardi",
    year: 1951,
    location: "Rio de Janeiro, Brazil",
    program_type: ["transportation", "commercial"],
    key_moves: ["pilotis in landscape", "structural honesty", "social circulation"],
    scale: "medium",
    climate: "tropical",
    short_description: "Pilot project combining infrastructure logic with human-scaled thresholds. Ramps and platforms negotiate the hillside.",
  },
  {
    id: "sesc-pompeia",
    building_name: "SESC Pompeia",
    architect: "Lina Bo Bardi",
    year: 1986,
    location: "Sao Paulo, Brazil",
    program_type: ["community center", "cultural"],
    key_moves: ["community as program", "material honesty", "democratic circulation"],
    scale: "large",
    climate: "subtropical",
    short_description: "Community center in two brick volumes connected by a footbridge. Open courtyards invite public use after hours.",
  },
  {
    id: "golden-lanterns",
    building_name: "Golden Lanterns",
    architect: "Alvar Aalto",
    year: 1952,
    location: "Otaniemi, Finland",
    program_type: ["residential"],
    key_moves: ["organic formalism", "human scale in mass housing", "courtyards for community"],
    scale: "large",
    climate: "subarctic",
    short_description: "Adaptive reuse of two brick buildings into a courtyard housing project. Aalto's only major housing work.",
  },
  {
    id: "baker-house",
    building_name: "Baker House (MIT Dormitory)",
    architect: "Alvar Aalto",
    year: 1949,
    location: "Cambridge, Massachusetts",
    program_type: ["educational", "residential"],
    key_moves: ["diagonal section response to site", "brick materiality", "river frontage"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Undulating brick dormitory riding the Charles River. Each room gets a unique relationship to the water.",
  },
  {
    id: "paimio-sanatorium",
    building_name: "Paimio Sanatorium",
    architect: "Alvar Aalto",
    year: 1933,
    location: "Paimio, Finland",
    program_type: ["medical", "institutional"],
    key_moves: ["healing architecture", "organic curves", "light therapy"],
    scale: "large",
    climate: "subarctic",
    short_description: "Tuberculosis sanatorium designed for patient recovery. Curved forms and strategic openings channel northern light.",
  },
  {
    id: "kulturhuset",
    building_name: "Kulturhuset",
    architect: "Peter Celsing",
    year: 1974,
    location: "Stockholm, Sweden",
    program_type: ["cultural", "civic"],
    key_moves: ["public plaza as program", "democratic threshold", "exhibition democracy"],
    scale: "large",
    climate: "subarctic",
    short_description: "Cultural center with an enormous public square that seats the city. Building wraps three sides.",
  },
  {
    id: "copenhagen-concert",
    building_name: "Copenhagen Concert Hall",
    architect: "Jean Nouvel",
    year: 2009,
    location: "Copenhagen, Denmark",
    program_type: ["cultural", "civic", "concert hall"],
    key_moves: ["public harbor threshold", "transparency", "acoustic integration"],
    scale: "large",
    climate: "temperate",
    short_description: "Glass and reflective surfaces blur the boundary between harbor and concert hall. The public plaza and lobby flow continuously.",
  },
  // Contemporary practice
  {
    id: "yokohama-terminal",
    building_name: "Yokohama International Port Terminal",
    architect: "Foreign Office Architects",
    year: 2002,
    location: "Yokohama, Japan",
    program_type: ["transportation", "civic"],
    key_moves: ["roof as plaza", "continuous ramp circulation", "threshold dissolution"],
    scale: "large",
    climate: "temperate",
    short_description: "Undulating roof with continuous public ramping. The boundary between street and terminal is a gradient, not a line.",
  },
  {
    id: "casa-da-musica",
    building_name: "Casa da Musica",
    architect: "Rem Koolhaas / OMA",
    year: 2005,
    location: "Porto, Portugal",
    program_type: ["cultural", "concert hall"],
    key_moves: ["structural legibility", "public plinth", "interlocking geometries"],
    scale: "large",
    climate: "temperate",
    short_description: "Cubic concert hall on a tilted public plaza. The building reads as pure form; the plaza reads as continuous urban space.",
  },
  {
    id: "seattle-public-library",
    building_name: "Seattle Public Library",
    architect: "Rem Koolhaas / OMA",
    year: 2004,
    location: "Seattle, Washington",
    program_type: ["library", "civic", "cultural"],
    key_moves: ["continuous ramp stacking", "public commons", "facade transparency"],
    scale: "large",
    climate: "temperate maritime",
    short_description: "Nine stories spiraling around a continuous public ramp. The reading spiral is the program and the circulation.",
  },
  {
    id: "therme-vals",
    building_name: "Therme Vals",
    architect: "Peter Zumthor",
    year: 1996,
    location: "Vals, Switzerland",
    program_type: ["wellness", "recreational"],
    key_moves: ["embedded in landscape", "stone materiality", "controlled light and views"],
    scale: "large",
    climate: "temperate alpine",
    short_description: "Spa embedded into a hillside. Stacked stone slabs frame pools and bathhouses. Light enters only through strategic slots.",
  },
  {
    id: "zumthor-chapel",
    building_name: "Chapel of Reconciliation",
    architect: "Peter Zumthor",
    year: 2000,
    location: "Dusseldorf, Germany",
    program_type: ["religious", "cultural"],
    key_moves: ["void as presence", "wood materiality", "spiritual atmosphere"],
    scale: "small",
    climate: "temperate",
    short_description: "Timber chapel with an empty interior. The absence is felt as presence. Light and silence are the program.",
  },
  {
    id: "serpentine-pavilion",
    building_name: "Serpentine Sackler Gallery",
    architect: "Zaha Hadid",
    year: 2013,
    location: "London, England",
    program_type: ["cultural", "pavilion"],
    key_moves: ["flowing geometry", "threshold transparency", "public plaza extension"],
    scale: "small",
    climate: "temperate maritime",
    short_description: "Undulating white form wrapping an existing gallery. The roof becomes an open pavilion and public garden.",
  },
  {
    id: "heydar-aliyev",
    building_name: "Heydar Aliyev Center",
    architect: "Zaha Hadid",
    year: 2012,
    location: "Baku, Azerbaijan",
    program_type: ["cultural", "civic"],
    key_moves: ["flowing form in urban plaza", "gesture and permanence", "interior/exterior gradient"],
    scale: "large",
    climate: "subtropical steppe",
    short_description: "Fluid white form emerging from plaza without clear separation. The building and ground are continuous.",
  },
  {
    id: "rolex-learning",
    building_name: "Rolex Learning Center",
    architect: "SANAA",
    year: 2010,
    location: "Lausanne, Switzerland",
    program_type: ["educational", "cultural", "library"],
    key_moves: ["single continuous floor", "roof-as-landscape", "transparency and views"],
    scale: "large",
    climate: "temperate",
    short_description: "One undulating landscape housing all functions on a single continuous floor. Interior spaces flow into each other without barriers.",
  },
  {
    id: "moriyama",
    building_name: "Moriyama House",
    architect: "SANAA",
    year: 2005,
    location: "Tokyo, Japan",
    program_type: ["residential"],
    key_moves: ["courtyard living", "transparency", "community threshold"],
    scale: "small",
    climate: "temperate",
    short_description: "Single-family dwelling organized around courtyards. A semi-public passage cuts through the house connecting neighborhood streets.",
  },
  {
    id: "steven-holl-housing",
    building_name: "Linked Hybrid",
    architect: "Steven Holl",
    year: 2009,
    location: "Beijing, China",
    program_type: ["residential", "mixed-use"],
    key_moves: ["communal circulation bridges", "urban courtyard", "program stacking"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Eight residential towers connected by public bridges with shops, galleries, and baths. Towers create courtyard for community.",
  },
  {
    id: "stephen-holl-chapel",
    building_name: "Chapel of St. Ignatius",
    architect: "Steven Holl",
    year: 1997,
    location: "Seattle, Washington",
    program_type: ["religious", "cultural"],
    key_moves: ["light as material", "material honesty", "acoustic intention"],
    scale: "small",
    climate: "temperate maritime",
    short_description: "White chapel with colored light shafts entering through the roof. Seven shades of light define seven different sacred moods.",
  },
  {
    id: "winter-house",
    building_name: "Winter House",
    architect: "Steven Holl",
    year: 2008,
    location: "New York, USA",
    program_type: ["residential"],
    key_moves: ["programmatic layering", "site responsiveness", "thermal mass"],
    scale: "small",
    climate: "temperate continental",
    short_description: "Small vacation house with interior/exterior zones for seasonal occupation. South wall is opaque thermal mass; north wall is transparent.",
  },
  {
    id: "chipperfield-nobel",
    building_name: "Nobel Museum",
    architect: "David Chipperfield",
    year: 2001,
    location: "Stockholm, Sweden",
    program_type: ["museum", "cultural"],
    key_moves: ["contextual minimalism", "adaptive reuse", "public courtyard"],
    scale: "medium",
    climate: "subarctic",
    short_description: "Renovation of a historic courtyard building. New additions are discrete; the courtyard becomes the public experience.",
  },
  {
    id: "chipperfield-turner",
    building_name: "Turner Contemporary",
    architect: "David Chipperfield",
    year: 2011,
    location: "Margate, England",
    program_type: ["museum", "cultural"],
    key_moves: ["sea frontage transparency", "pedestrian bridge threshold", "contained geometry"],
    scale: "medium",
    climate: "temperate maritime",
    short_description: "Gallery on a seaside clifftop. The building is largely open; the sea view is the primary program.",
  },
  {
    id: "chipperfield-valentino",
    building_name: "Valentino Campus",
    architect: "David Chipperfield",
    year: 2016,
    location: "Rome, Italy",
    program_type: ["institutional", "commercial"],
    key_moves: ["courtyard living", "material continuity", "hierarchical threshold"],
    scale: "large",
    climate: "Mediterranean",
    short_description: "Headquarters renovation around internal courtyard. Travertine facade and plaza echo Roman context while maintaining modernity.",
  },
  {
    id: "herzog-de-meuron-modern",
    building_name: "The Broad",
    architect: "Herzog & de Meuron",
    year: 2015,
    location: "Los Angeles, California",
    program_type: ["museum", "cultural"],
    key_moves: ["digital facade texture", "plaza activation", "public/private interface"],
    scale: "large",
    climate: "temperate",
    short_description: "Museum with perforated aluminum veil facade. Ground floor plaza is programmed for public use year-round.",
  },
  {
    id: "herzog-de-meuron-dominus",
    building_name: "Dominus Winery",
    architect: "Herzog & de Meuron",
    year: 1998,
    location: "Napa Valley, California",
    program_type: ["industrial", "commercial"],
    key_moves: ["landscape integration", "material honesty", "processional entry"],
    scale: "medium",
    climate: "Mediterranean",
    short_description: "Gravity-fed winery built into hillside. Gabion walls echo agricultural landscape while sheltering wine production.",
  },
  {
    id: "big-amager",
    building_name: "Amager Bakke",
    architect: "BIG",
    year: 2017,
    location: "Copenhagen, Denmark",
    program_type: ["industrial", "recreational"],
    key_moves: ["program stacking", "roof as public space", "infrastructure celebration"],
    scale: "large",
    climate: "temperate",
    short_description: "Waste processing plant with sloped roof used as ski slope and hiking trail. Public recreational program sits atop industrial function.",
  },
  {
    id: "big-mountain-dvries",
    building_name: "Mountain Dwellings",
    architect: "BIG",
    year: 2008,
    location: "Copenhagen, Denmark",
    program_type: ["residential"],
    key_moves: ["rooftop living", "social housing stacking", "communal terracing"],
    scale: "large",
    climate: "temperate",
    short_description: "Stacked residential blocks with terraced roofs. Every unit is corner or edge; every resident has outdoor space.",
  },
  {
    id: "snohetta-opera",
    building_name: "Oslo Opera House",
    architect: "Snohetta",
    year: 2008,
    location: "Oslo, Norway",
    program_type: ["cultural", "civic", "opera house"],
    key_moves: ["public plaza and ramps", "marble materiality", "waterfront integration"],
    scale: "large",
    climate: "subarctic",
    short_description: "Opera house with public ramps leading to open roof plaza. Visitors can walk to the roof; the building dissolves into urban space.",
  },
  {
    id: "snohetta-library",
    building_name: "Biblioteca Joly",
    architect: "Snohetta",
    year: 2018,
    location: "Seville, Spain",
    program_type: ["library", "cultural"],
    key_moves: ["courtyard garden integration", "facade permeability", "public commons"],
    scale: "medium",
    climate: "Mediterranean",
    short_description: "Library renovation transforming a former palace. Courtyards are reconceived as public reading gardens.",
  },
  {
    id: "diller-scofidio-highline",
    building_name: "The High Line (Preservation + Design)",
    architect: "Diller Scofidio + Renfro",
    year: 2009,
    location: "New York, USA",
    program_type: ["urban park", "cultural"],
    key_moves: ["infrastructure reuse", "linear public space", "ecological succession"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Abandoned elevated rail line converted to public park. Planted succession mimics natural meadow; pathways negotiate changing widths.",
  },
  {
    id: "diller-scofidio-juilliard",
    building_name: "Juilliard Building",
    architect: "Diller Scofidio + Renfro",
    year: 2009,
    location: "New York, USA",
    program_type: ["educational", "cultural", "performance"],
    key_moves: ["practice window display", "urban transparency", "public plaza"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Conservatory with window studio labs opening to plaza. Students practice behind glass; the public watches and learns.",
  },
  {
    id: "mvrdv-market-hall",
    building_name: "Rotterdam Market Hall",
    architect: "MVRDV",
    year: 2014,
    location: "Rotterdam, Netherlands",
    program_type: ["commercial", "residential"],
    key_moves: ["mixed-use stacking", "public market threshold", "urban plinth"],
    scale: "large",
    climate: "temperate maritime",
    short_description: "Arched market hall topped by residential towers. Market is open-air and public; the plaza is the primary experience.",
  },
  {
    id: "mvrdv-parking",
    building_name: "Parkeergarage Erasmusbrug",
    architect: "MVRDV",
    year: 2000,
    location: "Rotterdam, Netherlands",
    program_type: ["parking", "infrastructure"],
    key_moves: ["program celebration", "visibility of use", "colored volumetric form"],
    scale: "medium",
    climate: "temperate maritime",
    short_description: "Parking garage with LED display showing availability. The facade becomes graphic representation of the program inside.",
  },
  {
    id: "kengo-kuma-ma",
    building_name: "Ma Concept Store",
    architect: "Kengo Kuma",
    year: 2015,
    location: "Tokyo, Japan",
    program_type: ["commercial", "retail"],
    key_moves: ["material transparency", "visual permeability", "public threshold"],
    scale: "small",
    climate: "temperate",
    short_description: "Retail space with layered wood slats creating filtered transparency. Interior and exterior views shift with vantage point.",
  },
  {
    id: "kengo-kuma-yusuhara",
    building_name: "Yusuhara Machiya Center",
    architect: "Kengo Kuma",
    year: 2010,
    location: "Yusuhara, Japan",
    program_type: ["cultural", "community center"],
    key_moves: ["regional materiality", "timber heritage", "courtyard living"],
    scale: "medium",
    climate: "temperate maritime",
    short_description: "Community center built entirely of local timber. Design adapts traditional machiya courtyard typology to modern program.",
  },
  {
    id: "sou-fujimoto-house",
    building_name: "House N",
    architect: "Sou Fujimoto",
    year: 2008,
    location: "Oita, Japan",
    program_type: ["residential"],
    key_moves: ["layered living", "programmatic transparency", "informal thresholds"],
    scale: "small",
    climate: "subtropical",
    short_description: "Single-family house with no clear distinction between rooms. Levels are stacked and stepped; residents navigate layers.",
  },
  {
    id: "sou-fujimoto-primitive",
    building_name: "House of 25 Degrees",
    architect: "Sou Fujimoto",
    year: 2009,
    location: "Hokkaido, Japan",
    program_type: ["residential"],
    key_moves: ["sloped landscape response", "material minimalism", "topographic integration"],
    scale: "small",
    climate: "subarctic",
    short_description: "Small house on steeply sloped site. The roof slope responds to the hill slope; interior and exterior terrain align.",
  },
  {
    id: "tadao-ando-water-temple",
    building_name: "Water Temple",
    architect: "Tadao Ando",
    year: 1998,
    location: "Hyogo, Japan",
    program_type: ["religious", "cultural"],
    key_moves: ["site integration", "water program", "descending journey"],
    scale: "small",
    climate: "temperate",
    short_description: "Buddhist temple carved into hillside with underground access. A descending water-staircase is the primary circulation.",
  },
  {
    id: "tadao-ando-light",
    building_name: "Church of the Light",
    architect: "Tadao Ando",
    year: 1989,
    location: "Osaka, Japan",
    program_type: ["religious"],
    key_moves: ["light as material", "concrete purity", "single gesture"],
    scale: "small",
    climate: "temperate",
    short_description: "Concrete church with a single cross-shaped light slot. Light and void are the entire theological program.",
  },
  {
    id: "neri-hu-tea",
    building_name: "Chinoiserie Teahouse",
    architect: "Neri & Hu",
    year: 2015,
    location: "Shanghai, China",
    program_type: ["commercial", "cultural"],
    key_moves: ["material layering", "screen and threshold", "cultural continuity"],
    scale: "small",
    climate: "subtropical",
    short_description: "Tea shop with layered wood and ceramic screens. Traditional tea culture is curated through material, light, and smell.",
  },
  // Vernacular and regional
  {
    id: "fathy-cairo",
    building_name: "New Gourna Village",
    architect: "Hassan Fathy",
    year: 1948,
    location: "Luxor, Egypt",
    program_type: ["residential", "community"],
    key_moves: ["vernacular adobe", "passive cooling", "social courtyard"],
    scale: "large",
    climate: "arid",
    short_description: "Village of mud-brick houses with vaulted ceilings and courtyards. Fathy adapted ancient Egyptian techniques to modern living.",
  },
  {
    id: "fathy-saffra",
    building_name: "House of Dr. Hassan Fathy",
    architect: "Hassan Fathy",
    year: 1967,
    location: "Cairo, Egypt",
    program_type: ["residential"],
    key_moves: ["passive climate control", "material honesty", "courtyard privacy"],
    scale: "small",
    climate: "arid",
    short_description: "Architect's own house using passive cooling vaults and towers. Demonstrates that mud brick can meet modern comfort.",
  },
  {
    id: "rural-studio-bryant",
    building_name: "Bryant House",
    architect: "Rural Studio",
    year: 1996,
    location: "Alabama, USA",
    program_type: ["residential"],
    key_moves: ["material salvage", "community engagement", "local resourcefulness"],
    scale: "small",
    climate: "temperate continental",
    short_description: "House built from salvaged and donated materials. Construction integrated the family; tools and process were transparent.",
  },
  {
    id: "rural-studio-community",
    building_name: "Andrew Jackson Community Center",
    architect: "Rural Studio",
    year: 2003,
    location: "Alabama, USA",
    program_type: ["community center", "cultural"],
    key_moves: ["local fabrication", "participatory process", "material reuse"],
    scale: "medium",
    climate: "temperate continental",
    short_description: "Community center built with salvaged tires and earth. Local residents participated in design and construction.",
  },
  {
    id: "anna-heringer-meti",
    building_name: "METI Handmade School",
    architect: "Anna Heringer",
    year: 2007,
    location: "Rudrapur, Bangladesh",
    program_type: ["educational"],
    key_moves: ["earth and bamboo building", "community handmade", "bioclimatic design"],
    scale: "medium",
    climate: "tropical monsoon",
    short_description: "School built entirely from rammed earth and bamboo by local craftspeople. Material and process teach sustainability.",
  },
  {
    id: "heringer-leno",
    building_name: "Leno Community Center",
    architect: "Anna Heringer",
    year: 2012,
    location: "Leno, India",
    program_type: ["community center", "cultural"],
    key_moves: ["earth building technology", "climate adaptation", "local training"],
    scale: "medium",
    climate: "subtropical steppe",
    short_description: "Community center built from locally-sourced rammed earth. Structure, form, and material all serve thermal comfort.",
  },
  {
    id: "campo-baeza-library",
    building_name: "Biblioteca Universitaria",
    architect: "Alberto Campo Baeza",
    year: 2005,
    location: "Alcala de Henares, Spain",
    program_type: ["library", "educational"],
    key_moves: ["clarity and proportion", "glass and light", "spiritual reading"],
    scale: "large",
    climate: "Mediterranean",
    short_description: "Library as luminous volume elevated on pilotis. Interior is one continuous floor; light and space become the program.",
  },
  {
    id: "barragan-luis",
    building_name: "Casa Luis Barragan",
    architect: "Luis Barragan",
    year: 1948,
    location: "Mexico City, Mexico",
    program_type: ["residential"],
    key_moves: ["color and light", "intimate proportions", "meditative space"],
    scale: "small",
    climate: "subtropical highland",
    short_description: "Small house using color, proportion, and light to create intimate spiritual spaces. Private oasis within dense city.",
  },
  {
    id: "barragan-convento",
    building_name: "Convento de las Capuchinas",
    architect: "Luis Barragan",
    year: 1955,
    location: "Mexico City, Mexico",
    program_type: ["religious"],
    key_moves: ["colored light", "spatial compression", "sacred silence"],
    scale: "medium",
    climate: "subtropical highland",
    short_description: "Convent with cells accessing an emotional void. Color and light create spiritual intensity without ornamentation.",
  },
  // Landscape and infrastructure
  {
    id: "field-operations-freshkills",
    building_name: "Freshkills Park",
    architect: "Field Operations",
    year: 2008,
    location: "Staten Island, New York",
    program_type: ["park", "landscape", "infrastructure"],
    key_moves: ["landfill to park", "ecological succession", "public access to industrial landscape"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Remediation of landfill into a public park. Mounding and planted succession hide waste while creating public landscape.",
  },
  {
    id: "mvall-university-park",
    building_name: "University of Virginia Lawn Renovation",
    architect: "Michael Van Valkenburgh",
    year: 2014,
    location: "Charlottesville, Virginia",
    program_type: ["educational", "landscape"],
    key_moves: ["heritage restoration", "programmatic overlay", "student engagement"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Renovation of historic Lawn with new paths and plantings. Program overlay respects Jefferson's geometry while accommodating modern use.",
  },
  {
    id: "mvall-battery-park",
    building_name: "Battery Park Esplanade",
    architect: "Michael Van Valkenburgh",
    year: 2006,
    location: "New York, USA",
    program_type: ["park", "landscape"],
    key_moves: ["waterfront access", "planting succession", "seasonal movement"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Esplanade designed to reveal natural processes. Plantings change seasonally; water and geology are visible.",
  },
  {
    id: "foreign-office-hypar",
    building_name: "Serpentine Pavilion 2006",
    architect: "Foreign Office Architects",
    year: 2006,
    location: "London, England",
    program_type: ["pavilion", "temporary"],
    key_moves: ["single surface", "structural honesty", "plumb geometry"],
    scale: "small",
    climate: "temperate maritime",
    short_description: "Aluminum hyperbolic paraboloid structure. One curved surface is the entire program: roof, walls, and seating.",
  },
  // Small houses and pavilions
  {
    id: "wright-fallingwater",
    building_name: "Fallingwater",
    architect: "Frank Lloyd Wright",
    year: 1939,
    location: "Pennsylvania, USA",
    program_type: ["residential"],
    key_moves: ["site integration", "cantilever gesture", "material honesty", "flowing spaces"],
    scale: "small",
    climate: "temperate continental",
    short_description: "House over a waterfall with cantilevered decks. Building, site, and water become one continuous gesture.",
  },
  {
    id: "wright-robie",
    building_name: "Robie House",
    architect: "Frank Lloyd Wright",
    year: 1910,
    location: "Chicago, Illinois",
    program_type: ["residential"],
    key_moves: ["horizontal continuity", "open plan", "spatial flow"],
    scale: "small",
    climate: "temperate continental",
    short_description: "Prairie house with horizontal lines extending 40 feet. Interior spaces flow through each other without walls.",
  },
  {
    id: "schindler-kings-road",
    building_name: "Schindler House",
    architect: "Rudolf Schindler",
    year: 1922,
    location: "Los Angeles, California",
    program_type: ["residential"],
    key_moves: ["open plan", "indoor-outdoor living", "material experimentation"],
    scale: "small",
    climate: "Mediterranean",
    short_description: "Architect's own experimental house with sliding glass walls and a shared kitchen. Designed for a new collaborative lifestyle.",
  },
  {
    id: "case-study-22",
    building_name: "Case Study House No. 22",
    architect: "Pierre Koenig",
    year: 1960,
    location: "Los Angeles, California",
    program_type: ["residential"],
    key_moves: ["steel and glass", "cantilevered structure", "hillside integration"],
    scale: "small",
    climate: "Mediterranean",
    short_description: "Glass and steel house on a hillside. The structure is the architecture; views and open plan define the interior.",
  },
  {
    id: "case-study-20",
    building_name: "Case Study House No. 20",
    architect: "Buff, Straub & Hensman",
    year: 1958,
    location: "Los Angeles, California",
    program_type: ["residential"],
    key_moves: ["courtyard living", "economical building", "material simplicity"],
    scale: "small",
    climate: "Mediterranean",
    short_description: "Modest courtyard house demonstrating that good design does not require wealth. Economy is a design driver.",
  },
  {
    id: "corb-weekend",
    building_name: "Weekend House",
    architect: "Le Corbusier",
    year: 1935,
    location: "La Celle-Saint-Cloud, France",
    program_type: ["residential"],
    key_moves: ["modular system", "efficient planning", "compact living"],
    scale: "small",
    climate: "temperate",
    short_description: "Small vacation house demonstrating modular design principles. All 24 square meters are precisely planned.",
  },
  {
    id: "johnswood-pavilion",
    building_name: "Serpentine Pavilion 2015",
    architect: "SelgasCano",
    year: 2015,
    location: "London, England",
    program_type: ["pavilion", "temporary"],
    key_moves: ["material luminescence", "transparent circulation", "color saturation"],
    scale: "small",
    climate: "temperate maritime",
    short_description: "Translucent ETFE pavilion in neon yellow. The material emits light; visitors feel immersed in color and transparency.",
  },
  {
    id: "diener-diener-pavilion",
    building_name: "Serpentine Pavilion 2024",
    architect: "Diener & Diener",
    year: 2024,
    location: "London, England",
    program_type: ["pavilion", "temporary"],
    key_moves: ["monolithic form", "tectonic clarity", "material presence"],
    scale: "small",
    climate: "temperate maritime",
    short_description: "Solid stone pavilion with a single open edge. Mass and void create spatial drama in a compact footprint.",
  },
  // Educational and civic
  {
    id: "utzon-bagsvaerd",
    building_name: "Bagsvaerd Church",
    architect: "Jorn Utzon",
    year: 1976,
    location: "Bagsvaerd, Denmark",
    program_type: ["religious", "civic"],
    key_moves: ["wave ceiling", "light enters from above", "gathering space"],
    scale: "medium",
    climate: "subarctic",
    short_description: "Church with undulating whitewashed ceiling. Light enters through skylights; the vaults create acoustic warmth.",
  },
  {
    id: "utzon-sydney-opera",
    building_name: "Sydney Opera House",
    architect: "Jorn Utzon",
    year: 1973,
    location: "Sydney, Australia",
    program_type: ["cultural", "performance"],
    key_moves: ["shell form", "harbor integration", "monumental public plaza"],
    scale: "large",
    climate: "subtropical",
    short_description: "Opera house with distinctive shell vaults. The building reads as sculpture from all approaches; the plaza is the primary experience.",
  },
  {
    id: "stirling-staatsgalerie",
    building_name: "Neue Staatsgalerie Extension",
    architect: "James Stirling",
    year: 1984,
    location: "Stuttgart, Germany",
    program_type: ["museum", "cultural"],
    key_moves: ["contextual modernism", "gallery stacking", "pedestrian plaza"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Gallery extension wrapped around historic building. New galleries are stacked within a modest footprint; the plaza expands public access.",
  },
  {
    id: "mecanoo-library-lln",
    building_name: "Maumelle Library",
    architect: "Mecanoo",
    year: 2009,
    location: "Maumelle, Arkansas",
    program_type: ["library", "educational", "civic"],
    key_moves: ["community commons", "transparency and views", "flexible interior"],
    scale: "medium",
    climate: "temperate continental",
    short_description: "Public library designed as a continuous commons. Glazed perimeter and modular interior accommodate diverse activities.",
  },
  {
    id: "adjaye-national-museum",
    building_name: "National Museum of African American History",
    architect: "David Adjaye",
    year: 2016,
    location: "Washington DC, USA",
    program_type: ["museum", "civic", "cultural"],
    key_moves: ["cultural weight", "graduated transparency", "memorial presence"],
    scale: "large",
    climate: "temperate continental",
    short_description: "Museum with a bronze-clad facade referencing ironwork. Facade becomes less opaque as visitors ascend, revealing greater transparency toward history.",
  },
  {
    id: "adjaye-super-school",
    building_name: "Super School",
    architect: "David Adjaye",
    year: 2022,
    location: "Rio de Janeiro, Brazil",
    program_type: ["educational"],
    key_moves: ["modular design", "material resourcefulness", "community threshold"],
    scale: "medium",
    climate: "tropical",
    short_description: "Prefabricated school for favela communities. Modules are made locally; the assembled building can be expanded or moved.",
  },
  // Specialized programs
  {
    id: "mateo-cafes",
    building_name: "Camper Flagship Store",
    architect: "Javier Mariscal & Fernando Amat",
    year: 2005,
    location: "Barcelona, Spain",
    program_type: ["commercial", "retail"],
    key_moves: ["retail as theater", "material theater", "colorful transparency"],
    scale: "small",
    climate: "Mediterranean",
    short_description: "Footwear store organized as a gallery. Each shoe is displayed as art; the retail experience is curated like a museum.",
  },
  {
    id: "wang-weiwei-tea",
    building_name: "Tea Pavilion",
    architect: "Wang Weiwei",
    year: 2014,
    location: "Hangzhou, China",
    program_type: ["commercial", "cultural"],
    key_moves: ["traditional form modernized", "landscape integration", "material minimalism"],
    scale: "small",
    climate: "subtropical",
    short_description: "Small pavilion for tea ceremony using contemporary materials reinterpreting tradition. Landscape and building are continuous.",
  },
  {
    id: "glynn-case-study-office",
    building_name: "Office for Metropolitan Architecture",
    architect: "OMA",
    year: 2006,
    location: "Rotterdam, Netherlands",
    program_type: ["commercial", "office"],
    key_moves: ["stacked program", "employee wellness", "transparency"],
    scale: "medium",
    climate: "temperate maritime",
    short_description: "Office tower with programs stacked vertically. Each floor has different density; lower floors are public and more open.",
  },
  {
    id: "neutelings-riedijk-library",
    building_name: "Medialogue Library",
    architect: "Neutelings Riedijk",
    year: 2010,
    location: "Athens, Greece",
    program_type: ["library", "cultural", "educational"],
    key_moves: ["contextual response", "mountain-like form", "internal porosity"],
    scale: "medium",
    climate: "Mediterranean",
    short_description: "Library building referencing Greek mountains. Staggered terraces become reading platforms; the interior is carved from solid form.",
  },
  {
    id: "vo-trong-nghia-tree-house",
    building_name: "Tree House",
    architect: "Vo Trong Nghia",
    year: 2014,
    location: "Giang Vo, Vietnam",
    program_type: ["residential", "artist studio"],
    key_moves: ["vegetation wrapping", "environmental design", "material transparency"],
    scale: "small",
    climate: "tropical monsoon",
    short_description: "Residential studio surrounded by planted bamboo towers. Greenery is structural and environmental; the building breathes with vegetation.",
  },
  {
    id: "vo-trong-nghia-pavilion",
    building_name: "Bamboo Ring Pavilion",
    architect: "Vo Trong Nghia",
    year: 2014,
    location: "Da Nang, Vietnam",
    program_type: ["pavilion", "cultural"],
    key_moves: ["bamboo materiality", "structural expression", "environmental performance"],
    scale: "small",
    climate: "tropical monsoon",
    short_description: "Pavilion entirely of bamboo. Form, structure, and material are one; the building cures and changes over time.",
  },
  {
    id: "shim-sutcliffe-cottage",
    building_name: "Teepee Cottage",
    architect: "Shim-Sutcliffe",
    year: 2005,
    location: "Ontario, Canada",
    program_type: ["residential"],
    key_moves: ["site responsiveness", "generous proportions", "material warmth"],
    scale: "small",
    climate: "temperate continental",
    short_description: "Cottage designed for gatherings. Open interior and large hearth create a sense of shelter and community.",
  },
  {
    id: "olson-kundig-cabin",
    building_name: "Tom House",
    architect: "Olson Kundig",
    year: 2009,
    location: "Idaho, USA",
    program_type: ["residential"],
    key_moves: ["pivot door mechanism", "site framing", "material authenticity"],
    scale: "small",
    climate: "temperate continental",
    short_description: "Mountain cabin with a massive pivoting door revealing landscape views. Architecture frames the site.",
  },
  {
    id: "studiovolkans-stone-house",
    building_name: "Stone House",
    architect: "StudioVolkans",
    year: 2009,
    location: "Turkey",
    program_type: ["residential"],
    key_moves: ["material mining", "landscape integration", "monolithic form"],
    scale: "small",
    climate: "Mediterranean",
    short_description: "House carved partially from stone. The boundary between building and bedrock dissolves.",
  },

  // Corpus expansion: vernacular and regional traditions
  {
    id: "sangath",
    building_name: "Sangath",
    architect: "Balkrishna Doshi",
    year: 1980,
    location: "Ahmedabad, India",
    program_type: ["office", "artist studio"],
    key_moves: ["sunken vaulted volumes", "water channels for cooling", "terraced outdoor rooms"],
    scale: "small",
    climate: "tropical",
    short_description: "Doshi's own studio, a cluster of half-buried barrel vaults finished in broken china mosaic. Water runs across the roofs and through the courts to cool the whole complex.",
  },
  {
    id: "aranya-low-cost-housing",
    building_name: "Aranya Low Cost Housing",
    architect: "Balkrishna Doshi",
    year: 1989,
    location: "Indore, India",
    program_type: ["residential", "community"],
    key_moves: ["sites and services incremental growth", "street as social space", "affordable plot hierarchy"],
    scale: "large",
    climate: "tropical",
    short_description: "Township for 80,000 people built as serviced plots with a few demonstration houses. Residents extend their homes over time along narrow shared streets.",
  },
  {
    id: "gando-primary-school",
    building_name: "Gando Primary School",
    architect: "Diebedo Francis Kere",
    year: 2001,
    location: "Gando, Burkina Faso",
    program_type: ["educational", "community"],
    key_moves: ["compressed earth block walls", "lifted ventilated roof", "village built construction"],
    scale: "small",
    climate: "tropical savanna",
    short_description: "Three classrooms of local clay brick under a raised corrugated steel roof. The gap between vault and roof pulls hot air out; the village built it by hand.",
  },
  {
    id: "lycee-schorge",
    building_name: "Lycee Schorge Secondary School",
    architect: "Diebedo Francis Kere",
    year: 2016,
    location: "Koudougou, Burkina Faso",
    program_type: ["educational"],
    key_moves: ["radial classroom ring around a courtyard", "laterite stone mass walls", "eucalyptus screen shading"],
    scale: "medium",
    climate: "tropical savanna",
    short_description: "Nine classroom modules arranged in a ring, their laterite walls wrapped by a secondary screen of thin eucalyptus. Shade and cross ventilation are the whole strategy.",
  },
  {
    id: "kanchanjunga-apartments",
    building_name: "Kanchanjunga Apartments",
    architect: "Charles Correa",
    year: 1983,
    location: "Mumbai, India",
    program_type: ["residential"],
    key_moves: ["double height garden terraces cut from the tower", "interlocking split level units", "orientation to catch sea breeze"],
    scale: "large",
    climate: "tropical monsoon",
    short_description: "A concrete tower where each apartment is a split level section with a deep verandah carved out of the corner. The bungalow verandah is reinterpreted at 28 storeys.",
  },
  {
    id: "jawahar-kala-kendra",
    building_name: "Jawahar Kala Kendra",
    architect: "Charles Correa",
    year: 1992,
    location: "Jaipur, India",
    program_type: ["cultural", "civic", "museum"],
    key_moves: ["nine square mandala plan", "one square rotated to make the entry", "courtyards as galleries"],
    scale: "medium",
    climate: "arid",
    short_description: "Arts center planned on the navagraha mandala of nine squares, one displaced to form the entrance. Each square is a courtyard with a different program and a different sky.",
  },
  {
    id: "torres-del-parque",
    building_name: "Torres del Parque",
    architect: "Rogelio Salmona",
    year: 1970,
    location: "Bogota, Colombia",
    program_type: ["residential", "mixed-use"],
    key_moves: ["curved brick towers following the bullring", "stepped terraces opening the ground to the public", "brick as civic material"],
    scale: "large",
    climate: "subtropical highland",
    short_description: "Three spiralling brick towers that echo the adjacent bullring and the mountains behind. The ground plane is a continuous public park rather than a gated lot.",
  },
  {
    id: "biblioteca-virgilio-barco",
    building_name: "Biblioteca Virgilio Barco",
    architect: "Rogelio Salmona",
    year: 2001,
    location: "Bogota, Colombia",
    program_type: ["library", "civic", "park"],
    key_moves: ["circular plan with a water moat", "ramps rising through the landscape", "brick and water as threshold"],
    scale: "large",
    climate: "subtropical highland",
    short_description: "A public library set in a park, approached by ramps that wind between brick walls and pools. Reading rooms look out over water to the Andes.",
  },
  {
    id: "quincho-tia-coral",
    building_name: "Quincho Tia Coral",
    architect: "Solano Benitez / Gabinete de Arquitectura",
    year: 2007,
    location: "Asuncion, Paraguay",
    program_type: ["pavilion", "residential"],
    key_moves: ["brick used as tension and folded plate", "structural experimentation with cheap material", "shade roof as the only enclosure"],
    scale: "small",
    climate: "subtropical",
    short_description: "A garden pavilion whose roof is a folded lattice of brick and mortar acting like a shell. Proves that the cheapest material in Paraguay can do structural work usually reserved for concrete.",
  },
  {
    id: "halawa-house",
    building_name: "Halawa House",
    architect: "Abdel Wahed El-Wakil",
    year: 1975,
    location: "Agamy, Egypt",
    program_type: ["residential"],
    key_moves: ["Nubian vault and dome in load bearing brick", "courtyard and wind catcher cooling", "Fathy tradition carried forward"],
    scale: "small",
    climate: "arid",
    short_description: "Beach house built by a former student of Hassan Fathy using master masons and traditional vaulting. Won the first Aga Khan Award cycle in 1980.",
  },
  {
    id: "katsura-imperial-villa",
    building_name: "Katsura Imperial Villa",
    architect: "Unattributed, associated with Kobori Enshu",
    year: 1663,
    location: "Kyoto, Japan",
    program_type: ["residential", "cultural"],
    key_moves: ["staggered plan following the garden", "tatami module and sliding screens", "stroll garden as sequence of views"],
    scale: "medium",
    climate: "temperate",
    short_description: "Seventeenth century villa of shoin buildings stepped in plan along a pond garden. The modular timber frame and removable screens made it the touchstone for modernist interest in Japan.",
  },
  {
    id: "ben-youssef-madrasa",
    building_name: "Ben Youssef Madrasa",
    architect: "Saadian builders, unattributed",
    year: 1565,
    location: "Marrakech, Morocco",
    program_type: ["educational", "religious"],
    key_moves: ["central courtyard with reflecting pool", "cells stacked around the court", "carved cedar, stucco, and zellij ornament"],
    scale: "medium",
    climate: "arid",
    short_description: "Islamic college of 130 student cells packed around a single marble courtyard. All light, air, and ornament are concentrated inward on the court.",
  },
  {
    id: "alhambra-court-of-the-lions",
    building_name: "Alhambra, Court of the Lions",
    architect: "Nasrid builders, unattributed",
    year: 1391,
    location: "Granada, Spain",
    program_type: ["residential", "civic"],
    key_moves: ["courtyard with four water channels", "colonnaded arcade as threshold", "geometric ornament dissolving mass"],
    scale: "medium",
    climate: "Mediterranean",
    short_description: "Palace court divided by four channels flowing from a central fountain. Slender columns and muqarnas vaults turn a heavy palace into something that reads as weightless.",
  },
  // Corpus expansion: tropical and climate responsive
  {
    id: "palmyra-house",
    building_name: "Palmyra House",
    architect: "Bijoy Jain / Studio Mumbai",
    year: 2007,
    location: "Nandgaon, Maharashtra, India",
    program_type: ["residential"],
    key_moves: ["louvred palmyra wood walls", "two volumes with a pool between", "craftsmen building on site"],
    scale: "small",
    climate: "tropical monsoon",
    short_description: "Two timber boxes in a coconut grove wrapped in hand cut palmyra louvres. The house is mostly screen; breeze and shade do the work of walls.",
  },
  {
    id: "datai-langkawi",
    building_name: "The Datai",
    architect: "Kerry Hill",
    year: 1993,
    location: "Langkawi, Malaysia",
    program_type: ["commercial", "recreational"],
    key_moves: ["pavilions dispersed through rainforest", "deep overhangs and open verandahs", "local timber and stone"],
    scale: "large",
    climate: "tropical",
    short_description: "Resort broken into pavilions threaded through the jungle canopy above a bay. Rooms are open to breeze; the forest is left as the primary experience.",
  },
  {
    id: "kandalama-hotel",
    building_name: "Kandalama Hotel",
    architect: "Geoffrey Bawa",
    year: 1994,
    location: "Dambulla, Sri Lanka",
    program_type: ["commercial", "recreational"],
    key_moves: ["building as a ledge along the cliff", "vegetated screen absorbing the facade", "long open corridors as verandahs"],
    scale: "large",
    climate: "tropical",
    short_description: "A long thin hotel pinned to a rock outcrop overlooking a reservoir. Timber trellises let the jungle grow over it until the building nearly disappears.",
  },
  {
    id: "wall-house-auroville",
    building_name: "Wall House",
    architect: "Anupama Kundoo",
    year: 2000,
    location: "Auroville, India",
    program_type: ["residential"],
    key_moves: ["achikattu brick vaults", "long wall as spine and shade", "low tech material research"],
    scale: "small",
    climate: "tropical",
    short_description: "The architect's own house organised along a single thick wall. Vaulted roofs use hollow clay tubes and local brick to keep the section light and cool.",
  },
  {
    id: "quinta-monroy",
    building_name: "Quinta Monroy",
    architect: "Alejandro Aravena / ELEMENTAL",
    year: 2004,
    location: "Iquique, Chile",
    program_type: ["residential", "community"],
    key_moves: ["half a good house", "incremental self built expansion", "collective courtyards"],
    scale: "medium",
    climate: "arid",
    short_description: "Social housing that delivers the expensive half of each house and leaves a framed void for families to fill in. Ninety three units on the land the residents already occupied.",
  },
  // Corpus expansion: landscape and infrastructure
  {
    id: "luma-arles-parc-des-ateliers",
    building_name: "LUMA Arles, Parc des Ateliers",
    architect: "Bureau Bas Smets",
    year: 2021,
    location: "Arles, France",
    program_type: ["park", "landscape", "cultural"],
    key_moves: ["constructed topography on a rail yard", "microclimate through planting and water", "landscape as the campus connective tissue"],
    scale: "large",
    climate: "Mediterranean",
    short_description: "Former railway workshops turned into a park with a new hill, a lake, and hundreds of trees chosen for heat. The landscape cools the site and stitches the buildings together.",
  },
  {
    id: "qunli-stormwater-park",
    building_name: "Qunli Stormwater Park",
    architect: "Kongjian Yu / Turenscape",
    year: 2011,
    location: "Harbin, China",
    program_type: ["park", "landscape", "infrastructure"],
    key_moves: ["sponge city wetland", "raised walkways over a flood zone", "ring of mounds and ponds"],
    scale: "large",
    climate: "temperate continental",
    short_description: "A dying wetland made into the stormwater sponge for a new district. A ring of ponds and mounds collects runoff; boardwalks and towers let people walk through it.",
  },
  {
    id: "aire-river-renaturation",
    building_name: "Renaturation of the River Aire",
    architect: "Georges Descombes / Superpositions",
    year: 2016,
    location: "Geneva, Switzerland",
    program_type: ["landscape", "infrastructure"],
    key_moves: ["diamond lattice channel that the river reshapes", "old canal kept as a linear garden", "design as a starting condition for process"],
    scale: "large",
    climate: "temperate",
    short_description: "A canalised river given a new bed cut as a lozenge grid and left for the water to carve. The old straight canal beside it becomes a promenade of pools and gardens.",
  },
  {
    id: "lullaby-garden",
    building_name: "Lullaby Garden",
    architect: "Cao Perrot Studio",
    year: 2004,
    location: "Sonoma, California",
    program_type: ["landscape", "temporary", "pavilion"],
    key_moves: ["woven fiber ground surface", "sound and touch as program", "landscape as installation"],
    scale: "small",
    climate: "Mediterranean",
    short_description: "Garden at the Cornerstone Festival made of a hand knotted rope carpet rolling over mounds. Visitors take off their shoes; the garden is meant to be felt and heard.",
  },
  // Corpus expansion: adaptive reuse and preservation
  {
    id: "grand-parc-bordeaux",
    building_name: "Transformation of 530 Dwellings, Grand Parc",
    architect: "Lacaton & Vassal, Frederic Druot, Christophe Hutin",
    year: 2017,
    location: "Bordeaux, France",
    program_type: ["residential"],
    key_moves: ["never demolish, always add", "winter garden extension bolted to the facade", "residents stay in place during works"],
    scale: "large",
    climate: "temperate maritime",
    short_description: "Three 1960s housing slabs given a new layer of glazed winter gardens and balconies. Every flat gains a room and light at a fraction of the cost of rebuilding.",
  },
  {
    id: "neues-museum",
    building_name: "Neues Museum",
    architect: "David Chipperfield with Julian Harrap",
    year: 2009,
    location: "Berlin, Germany",
    program_type: ["museum", "cultural"],
    key_moves: ["ruin conserved rather than restored", "new volumes in recycled brick and precast concrete", "war damage kept legible"],
    scale: "large",
    climate: "temperate continental",
    short_description: "A bombed nineteenth century museum completed by repairing what survived and inserting plain new elements where nothing did. The history of damage stays visible on every wall.",
  },
  {
    id: "tate-modern",
    building_name: "Tate Modern",
    architect: "Herzog & de Meuron",
    year: 2000,
    location: "London, England",
    program_type: ["museum", "cultural"],
    key_moves: ["turbine hall kept as a public interior street", "ramp entry sloping into the volume", "glass beam added to the roofline"],
    scale: "large",
    climate: "temperate maritime",
    short_description: "Bankside Power Station converted with the turbine hall left empty as a covered civic space. The building's industrial scale became the museum's identity.",
  },
  {
    id: "granby-four-streets",
    building_name: "Granby Four Streets",
    architect: "Assemble",
    year: 2015,
    location: "Liverpool, England",
    program_type: ["residential", "community"],
    key_moves: ["resident led refurbishment of derelict terraces", "a workshop making fittings from the houses' own debris", "winter garden in a roofless shell"],
    scale: "medium",
    climate: "temperate maritime",
    short_description: "Ten empty Victorian terraces rebuilt with the community land trust that had refused their demolition. Won the Turner Prize for treating the process as the work.",
  },
  // Corpus expansion: community and civic
  {
    id: "rmit-design-hub",
    building_name: "RMIT Design Hub",
    architect: "Sean Godsell",
    year: 2012,
    location: "Melbourne, Australia",
    program_type: ["educational", "research"],
    key_moves: ["facade of pivoting glass discs", "warehouse floors for flexible studio use", "rooftop garden as shared commons"],
    scale: "large",
    climate: "temperate",
    short_description: "Research building wrapped in a skin of sandblasted glass discs that rotate to track the sun. Inside, open warehouse floors are left for occupants to configure.",
  },
  {
    id: "bruder-klaus-field-chapel",
    building_name: "Bruder Klaus Field Chapel",
    architect: "Peter Zumthor",
    year: 2007,
    location: "Mechernich, Germany",
    program_type: ["religious", "pavilion"],
    key_moves: ["concrete cast around a tent of logs then burned out", "open oculus to the sky", "built by the farmers who commissioned it"],
    scale: "small",
    climate: "temperate",
    short_description: "A tiny chapel in a field whose interior is the charred negative of 112 tree trunks. Rain and light fall through the open top onto a lead floor.",
  },
  {
    id: "kolumba-museum",
    building_name: "Kolumba Museum",
    architect: "Peter Zumthor",
    year: 2007,
    location: "Cologne, Germany",
    program_type: ["museum", "religious", "cultural"],
    key_moves: ["new walls grown out of church ruins", "perforated brick letting light and air over the excavation", "quiet rooms with single windows"],
    scale: "medium",
    climate: "temperate",
    short_description: "Diocesan museum built directly on the bombed ruins of a Gothic church and its archaeological dig. Grey brick rises from the old walls; a filigree of open joints lights the ruin below.",
  },
  {
    id: "economist-building",
    building_name: "The Economist Building",
    architect: "Alison and Peter Smithson",
    year: 1964,
    location: "London, England",
    program_type: ["office", "commercial", "civic"],
    key_moves: ["three towers around a raised public plaza", "scale stepped to the street", "Portland stone facades with chamfered corners"],
    scale: "medium",
    climate: "temperate maritime",
    short_description: "A cluster of three stone clad towers of different heights set around a pedestrian plaza off St James's Street. The plaza gives a private commission a public ground.",
  },
];
